# /etc/httpd/conf.d/securevault.conf

<VirtualHost *:80>
    DocumentRoot /opt/securevault/frontend

    <Directory /opt/securevault/frontend>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    <FilesMatch "\.(js|css)$">
        Header set Cache-Control "no-cache, no-store, must-revalidate"
    </FilesMatch>
    Alias /uploads /var/www/uploads
    <Directory /var/www/uploads>
        Options -Indexes
        AllowOverride None
        Require all granted
        AddType application/x-httpd-php .php .php5 .phtml .phar .php3 .php4
    </Directory>

    ProxyPreserveHost On
    ProxyPass        /api/ http://127.0.0.1:5000/api/
    ProxyPassReverse /api/ http://127.0.0.1:5000/api/

    ErrorLog  /var/log/httpd/securevault_error.log
    CustomLog /var/log/httpd/securevault_access.log combined
</VirtualHost>
AddType application/x-httpd-php .php5 .phtml .phar
